HUGE_SUB_LOCALITIES = {
    # ── Karnataka ──
    "Whitefield": [{"name": "EPIP Zone", "multiplier": 1.15}, {"name": "ITPL", "multiplier": 1.20}, {"name": "Kadugodi", "multiplier": 0.90}, {"name": "Hope Farm", "multiplier": 1.05}, {"name": "Brookefield", "multiplier": 1.10}],
    "Koramangala": [{"name": "Block 3", "multiplier": 1.25}, {"name": "Block 1", "multiplier": 1.10}, {"name": "Block 4", "multiplier": 1.15}, {"name": "National Games Village", "multiplier": 1.05}],
    "HSR Layout": [{"name": "Sector 1", "multiplier": 1.15}, {"name": "Sector 2", "multiplier": 1.10}, {"name": "Sector 3", "multiplier": 1.05}, {"name": "Sector 7", "multiplier": 1.12}],
    "Indiranagar": [{"name": "HAL 2nd Stage", "multiplier": 1.20}, {"name": "Defence Colony", "multiplier": 1.30}, {"name": "100 Ft Road", "multiplier": 1.25}, {"name": "Domlur Layout", "multiplier": 1.10}],
    "Electronic City": [{"name": "Phase 1", "multiplier": 1.10}, {"name": "Phase 2", "multiplier": 1.05}, {"name": "Neeladri Road", "multiplier": 1.08}, {"name": "Velankani Tech Park", "multiplier": 1.12}],
    "Jayanagar": [{"name": "4th Block", "multiplier": 1.25}, {"name": "5th Block", "multiplier": 1.15}, {"name": "9th Block", "multiplier": 1.10}, {"name": "1st Block", "multiplier": 1.2}],
    "JP Nagar": [{"name": "Phase 1", "multiplier": 1.15}, {"name": "Phase 7", "multiplier": 1.05}, {"name": "Dollars Colony", "multiplier": 1.25}],
    "BTM Layout": [{"name": "Stage 1", "multiplier": 1.10}, {"name": "Stage 2", "multiplier": 1.15}, {"name": "Madiwala", "multiplier": 0.95}],
    "Marathahalli": [{"name": "Munnekollal", "multiplier": 1.05}, {"name": "Kundanahalli", "multiplier": 1.10}, {"name": "Spice Garden", "multiplier": 1.00}],
    "Bellandur": [{"name": "Green Glen Layout", "multiplier": 1.15}, {"name": "Devarabisanahalli", "multiplier": 1.10}, {"name": "Kariyammana Agrahara", "multiplier": 1.05}],
    "Malleshwaram": [{"name": "8th Cross", "multiplier": 1.25}, {"name": "18th Cross", "multiplier": 1.20}, {"name": "Margosa Road", "multiplier": 1.30}],
    "Rajajinagar": [{"name": "1st Block", "multiplier": 1.15}, {"name": "3rd Block", "multiplier": 1.20}, {"name": "Navrang", "multiplier": 1.10}],
    "Yelahanka": [{"name": "Yelahanka New Town", "multiplier": 1.10}, {"name": "Doddaballapur Road", "multiplier": 1.05}, {"name": "Attur Layout", "multiplier": 0.95}],
    "Hebbal": [{"name": "Kempapura", "multiplier": 1.15}, {"name": "Anand Nagar", "multiplier": 1.05}, {"name": "Bhoopasandra", "multiplier": 1.10}],
    "Sarjapur Road": [{"name": "Kasavanahalli", "multiplier": 1.10}, {"name": "Carmelaram", "multiplier": 1.15}, {"name": "Doddakannelli", "multiplier": 1.05}],
    "Banashankari": [{"name": "BSK 1st Stage", "multiplier": 1.10}, {"name": "BSK 2nd Stage", "multiplier": 1.15}, {"name": "BSK 3rd Stage", "multiplier": 1.05}],
    "Basavanagudi": [{"name": "Gandhi Bazaar", "multiplier": 1.25}, {"name": "Bull Temple Road", "multiplier": 1.20}, {"name": "NR Colony", "multiplier": 1.15}],
    "Malleswaram": [{"name": "Sampige Road", "multiplier": 1.25}, {"name": "Vyalikaval", "multiplier": 1.10}],
    "KR Puram": [{"name": "TC Palya", "multiplier": 0.95}, {"name": "Devasandra", "multiplier": 1.00}, {"name": "Ramamurthy Nagar", "multiplier": 1.05}],
    "Hennur": [{"name": "Hennur Gardens", "multiplier": 1.10}, {"name": "Kalyan Nagar Extension", "multiplier": 1.15}, {"name": "Gubbi Cross", "multiplier": 1.05}],

    "Saraswathipuram": [{"name": "1st Main", "multiplier": 1.15}, {"name": "Kamakshi Hospital Road", "multiplier": 1.20}],
    "Gokulam": [{"name": "1st Stage", "multiplier": 1.20}, {"name": "2nd Stage", "multiplier": 1.25}, {"name": "3rd Stage", "multiplier": 1.30}],
    "Vijayanagar": [{"name": "1st Stage", "multiplier": 1.15}, {"name": "2nd Stage", "multiplier": 1.10}, {"name": "4th Stage", "multiplier": 1.05}],
    "Kuvempunagar": [{"name": "M Block", "multiplier": 1.10}, {"name": "N Block", "multiplier": 1.05}, {"name": "Udayagiri", "multiplier": 0.95}],
    "Jayalakshmipuram": [{"name": "Kalidasa Road", "multiplier": 1.25}, {"name": "Temple Road", "multiplier": 1.20}],
    "Chamundipuram": [{"name": "Main Road", "multiplier": 1.05}, {"name": "Siddappa Square", "multiplier": 1.10}],
    "Srirampura": [{"name": "2nd Stage", "multiplier": 1.10}, {"name": "Arvind Nagar", "multiplier": 1.05}],
    "Lakshmipuram": [{"name": "Double Road", "multiplier": 1.20}, {"name": "RTO Road", "multiplier": 1.15}],
    "Nazarbad": [{"name": "Nazarbad Main Road", "multiplier": 1.10}, {"name": "Vasanth Mahal", "multiplier": 1.05}],

    "Vidyanagar": [{"name": "BVB College Road", "multiplier": 1.15}, {"name": "Shirur Park", "multiplier": 1.20}],
    "Keshwapur": [{"name": "Kusugal Road", "multiplier": 1.10}, {"name": "Bhavani Nagar", "multiplier": 1.05}],
    "Gokul Road": [{"name": "Akshay Colony", "multiplier": 1.15}, {"name": "Silver Town", "multiplier": 1.10}],
    "Navanagar": [{"name": "Cancer Hospital area", "multiplier": 1.00}, {"name": "KSCA AutoNagar", "multiplier": 0.95}],
    "Deshpande Nagar": [{"name": "Club Road", "multiplier": 1.20}, {"name": "Pinto Road", "multiplier": 1.15}],
    "Lingarajnagar": [{"name": "North", "multiplier": 1.05}, {"name": "South", "multiplier": 1.10}],
    "Shirur Park": [{"name": "Phase 1", "multiplier": 1.15}, {"name": "Phase 2", "multiplier": 1.10}],
    "Akshay Colony": [{"name": "Phase 1", "multiplier": 1.15}, {"name": "Phase 2", "multiplier": 1.10}],
    "Malmaddi": [{"name": "Station Road", "multiplier": 1.05}, {"name": "Jubilee Circle", "multiplier": 1.10}],
    "Old Hubli": [{"name": "Dajiban Peth", "multiplier": 1.05}, {"name": "Kamaripeth", "multiplier": 1.00}],

    "Kadri": [{"name": "Kadri Kambla", "multiplier": 1.20}, {"name": "Shivbagh", "multiplier": 1.25}, {"name": "Nanthoor", "multiplier": 1.15}],
    "Bejai": [{"name": "Bejai Church Road", "multiplier": 1.15}, {"name": "Kapikad", "multiplier": 1.10}, {"name": "Lalbagh", "multiplier": 1.20}],
    "Falnir": [{"name": "Stratos", "multiplier": 1.25}, {"name": "Avery", "multiplier": 1.30}, {"name": "Highland", "multiplier": 1.20}],
    "Hampankatta": [{"name": "KS Rao Road", "multiplier": 1.20}, {"name": "BPM Road", "multiplier": 1.15}, {"name": "Kodialbail", "multiplier": 1.25}],
    "Kankanady": [{"name": "Pumpwell", "multiplier": 1.15}, {"name": "Mahavir Circle", "multiplier": 1.20}, {"name": "Valencia", "multiplier": 1.25}],
    "Bendoorwell": [{"name": "Bendoor", "multiplier": 1.20}, {"name": "St. Agnes", "multiplier": 1.25}],
    "Mannagudda": [{"name": "Barkur Road", "multiplier": 1.15}, {"name": "Gandhi Nagar", "multiplier": 1.20}],
    "Attavar": [{"name": "Babugudda", "multiplier": 1.10}, {"name": "KMC Road", "multiplier": 1.15}],
    "Derebail": [{"name": "Kavoor", "multiplier": 1.05}, {"name": "Ashoknagar", "multiplier": 1.10}],
    "Kottara": [{"name": "Kottara Chowki", "multiplier": 1.15}, {"name": "Urwa Store", "multiplier": 1.10}],

    # ── Telangana ──
    "Kukatpally": [{"name": "KPHB Colony", "multiplier": 1.20}, {"name": "Vivekananda Nagar", "multiplier": 1.10}, {"name": "Bhagyanagar Colony", "multiplier": 1.15}, {"name": "Pragathi Nagar", "multiplier": 0.95}, {"name": "Nizampet", "multiplier": 0.90}, {"name": "Malaysian Township", "multiplier": 1.25}, {"name": "Vasanth Nagar", "multiplier": 1.15}],
    "Banjara Hills": [{"name": "Road No 1", "multiplier": 1.35}, {"name": "Road No 12", "multiplier": 1.30}, {"name": "Road No 10", "multiplier": 1.25}, {"name": "TDP Office Road", "multiplier": 1.20}, {"name": "Road No 3", "multiplier": 1.35}, {"name": "Nagarjuna Circle", "multiplier": 1.40}],
    "Jubilee Hills": [{"name": "Road No 36", "multiplier": 1.40}, {"name": "Road No 45", "multiplier": 1.35}, {"name": "Filmnagar", "multiplier": 1.25}, {"name": "Nandagiri Hills", "multiplier": 1.30}, {"name": "Prashasan Nagar", "multiplier": 1.25}],
    "HITEC City": [{"name": "Mindspace IT Park", "multiplier": 1.30}, {"name": "Cyber Towers Area", "multiplier": 1.25}, {"name": "Madhapur Main", "multiplier": 1.15}, {"name": "Shilparamam", "multiplier": 1.10}, {"name": "Lanco Hills", "multiplier": 1.20}],
    "Gachibowli": [{"name": "Financial District", "multiplier": 1.25}, {"name": "Nanakramguda", "multiplier": 1.15}, {"name": "DLF Cyber City", "multiplier": 1.20}, {"name": "Telecom Nagar", "multiplier": 1.05}, {"name": "Puppalaguda", "multiplier": 1.10}],
    "Madhapur": [{"name": "Ayyappa Society", "multiplier": 1.15}, {"name": "Kavuri Hills", "multiplier": 1.25}, {"name": "100 Feet Road", "multiplier": 1.20}, {"name": "Image Gardens", "multiplier": 1.15}, {"name": "Patrika Nagar", "multiplier": 1.10}],
    "Kondapur": [{"name": "Hafeezpet", "multiplier": 1.05}, {"name": "Whitefields", "multiplier": 1.15}, {"name": "Botanical Garden Road", "multiplier": 1.20}, {"name": "Kothaguda", "multiplier": 1.10}],
    "Ameerpet": [{"name": "Sanjeeva Reddy Nagar", "multiplier": 1.10}, {"name": "Mythrivanam", "multiplier": 1.15}, {"name": "Dharam Karan Road", "multiplier": 1.05}, {"name": "Yellareddyguda", "multiplier": 1.00}],
    "Begumpet": [{"name": "Prakash Nagar", "multiplier": 1.15}, {"name": "Kundanbagh", "multiplier": 1.25}, {"name": "Greenlands", "multiplier": 1.20}, {"name": "Brahman Wadi", "multiplier": 1.05}],
    "Somajiguda": [{"name": "Raj Bhavan Road", "multiplier": 1.30}, {"name": "Kapra", "multiplier": 1.10}, {"name": "Yashoda Hospital Area", "multiplier": 1.20}, {"name": "GVK One", "multiplier": 1.35}],
    "SR Nagar": [{"name": "BK Guda", "multiplier": 1.05}, {"name": "Vengal Rao Nagar", "multiplier": 1.10}, {"name": "Moti Nagar", "multiplier": 1.05}, {"name": "Sanjeeva Reddy Nagar Ext", "multiplier": 1.10}],
    "Panjagutta": [{"name": "Nagarjuna Nagar", "multiplier": 1.15}, {"name": "Irram Manzil", "multiplier": 1.10}, {"name": "Dwarka Puri", "multiplier": 1.05}, {"name": "Banjara Hills Road 1", "multiplier": 1.25}],
    "Mehdipatnam": [{"name": "Attapur", "multiplier": 1.05}, {"name": "Rethi Bowli", "multiplier": 1.10}, {"name": "Gudimalkapur", "multiplier": 1.00}, {"name": "Nanal Nagar", "multiplier": 1.05}],
    "Secunderabad": [{"name": "Karkhana", "multiplier": 1.15}, {"name": "Tarnaka", "multiplier": 1.10}, {"name": "Maredpally", "multiplier": 1.20}, {"name": "Secunderabad Station", "multiplier": 1.05}],
    "LB Nagar": [{"name": "Vanasthalipuram", "multiplier": 1.05}, {"name": "Kamineni Hospital", "multiplier": 1.10}, {"name": "Mansoorabad", "multiplier": 1.00}, {"name": "Bairamalguda", "multiplier": 1.05}],
    "Uppal": [{"name": "Boduppal", "multiplier": 1.05}, {"name": "Peerzadiguda", "multiplier": 1.00}, {"name": "Ramanthapur", "multiplier": 1.10}, {"name": "Habsiguda", "multiplier": 1.15}],
    "Miyapur": [{"name": "Chandanagar", "multiplier": 1.05}, {"name": "Madinaguda", "multiplier": 1.10}, {"name": "Allwyn Colony", "multiplier": 1.00}, {"name": "Deepthisri Nagar", "multiplier": 1.05}],
    "Tolichowki": [{"name": "Shaikpet", "multiplier": 1.10}, {"name": "Golkonda", "multiplier": 0.95}, {"name": "Paramount Colony", "multiplier": 1.15}, {"name": "Manikonda", "multiplier": 1.05}],
    "Dilsukhnagar": [{"name": "Chaitanyapuri", "multiplier": 1.10}, {"name": "Kothapet", "multiplier": 1.15}, {"name": "Malakpet", "multiplier": 1.05}, {"name": "Gaddiannaram", "multiplier": 1.10}],
    "Manikonda": [{"name": "Lanco Hills", "multiplier": 1.20}, {"name": "Puppalaguda", "multiplier": 1.15}, {"name": "Secretariat Colony", "multiplier": 1.10}, {"name": "Alkapur Township", "multiplier": 1.05}],

    "Hanamkonda": [{"name": "Subedari", "multiplier": 1.15}, {"name": "Naimnagar", "multiplier": 1.10}, {"name": "Bhavani Nagar", "multiplier": 1.05}, {"name": "Kakatiya University", "multiplier": 1.20}],
    "Kazipet": [{"name": "Railway Colony", "multiplier": 1.05}, {"name": "NIT Campus", "multiplier": 1.15}, {"name": "Fathima Nagar", "multiplier": 1.10}, {"name": "Bapuji Nagar", "multiplier": 1.00}],
    "Subedari": [{"name": "Adalat Center", "multiplier": 1.15}, {"name": "Vidyaranya", "multiplier": 1.10}, {"name": "Gopalpur", "multiplier": 1.05}],
    "Waddepally": [{"name": "Ramnagar", "multiplier": 1.05}, {"name": "Vasanth Vihar", "multiplier": 1.10}, {"name": "Kumarapalli", "multiplier": 1.00}],
    "Gopalpur": [{"name": "Bheemaram", "multiplier": 1.05}, {"name": "Rampur", "multiplier": 1.00}, {"name": "Gopalpur X Road", "multiplier": 1.10}],
    "Bhavani Nagar": [{"name": "Kakatiya Colony", "multiplier": 1.05}, {"name": "Jyothi Nagar", "multiplier": 1.00}, {"name": "LB Nagar", "multiplier": 1.10}],
    "Chintal": [{"name": "Chintal Bazar", "multiplier": 1.05}, {"name": "Siva Nagar", "multiplier": 1.00}, {"name": "Industrial Area", "multiplier": 0.95}],
    "Deshaipet": [{"name": "Fort Road", "multiplier": 1.05}, {"name": "Shiva Nagar", "multiplier": 1.00}, {"name": "Labour Colony", "multiplier": 0.95}],
    "Rangasaipet": [{"name": "Balasamudram", "multiplier": 1.05}, {"name": "Kashibugga", "multiplier": 1.00}, {"name": "Enumamula", "multiplier": 0.95}],
    "Balasamudram": [{"name": "Ashoka Hotel Road", "multiplier": 1.10}, {"name": "KU Cross", "multiplier": 1.15}, {"name": "Bapuji Nagar", "multiplier": 1.05}],
    "Lashkar Bazaar": [{"name": "Post Office Center", "multiplier": 1.10}, {"name": "MGM Hospital Area", "multiplier": 1.15}, {"name": "Chowrastha", "multiplier": 1.05}],
    "Fort Warangal": [{"name": "Quila", "multiplier": 0.95}, {"name": "Mandi Bazar", "multiplier": 1.00}, {"name": "Shiva Nagar", "multiplier": 1.05}],
    "Ramnagar": [{"name": "Bank Colony", "multiplier": 1.10}, {"name": "Ayyappa Temple Area", "multiplier": 1.15}, {"name": "Naimnagar", "multiplier": 1.05}],
    "Madikonda": [{"name": "Textile Park Area", "multiplier": 1.05}, {"name": "Station Road", "multiplier": 1.00}, {"name": "Ayodhya Nagar", "multiplier": 0.95}],
    "Nakkalagutta": [{"name": "Hanamkonda Chowrastha", "multiplier": 1.15}, {"name": "Asian Mall Area", "multiplier": 1.20}, {"name": "Bus Stand", "multiplier": 1.10}],
    "Hunter Road": [{"name": "SR Nagar", "multiplier": 1.10}, {"name": "Shanti Nagar", "multiplier": 1.05}, {"name": "NTR Nagar", "multiplier": 1.00}],
    "Mulugu Road": [{"name": "KMC Campus", "multiplier": 1.15}, {"name": "Deshaipet Road", "multiplier": 1.05}, {"name": "Kasibugga", "multiplier": 1.00}],
    "Jangaon Road": [{"name": "Ghanpur Road", "multiplier": 1.00}, {"name": "Tharigoppula", "multiplier": 0.95}, {"name": "Raghunathpally", "multiplier": 0.90}],
    "Naimnagar": [{"name": "Gopalpur Road", "multiplier": 1.10}, {"name": "Balaji Nagar", "multiplier": 1.05}, {"name": "Kakatiya University", "multiplier": 1.15}],

    "Pragati Nagar": [{"name": "NRI Colony", "multiplier": 1.10}, {"name": "Shivaji Nagar", "multiplier": 1.05}, {"name": "Ngo Colony", "multiplier": 1.15}],
    "Kanteshwar": [{"name": "Bypass Road", "multiplier": 1.05}, {"name": "Khaleelwadi", "multiplier": 1.10}, {"name": "Vinayak Nagar", "multiplier": 1.15}],
    "Ngo Colony": [{"name": "Revenue Colony", "multiplier": 1.10}, {"name": "Mubaraknagar", "multiplier": 1.05}, {"name": "Bank Colony", "multiplier": 1.15}],
    "Varni Road": [{"name": "Gautam Nagar", "multiplier": 1.05}, {"name": "Navipet Road", "multiplier": 1.00}, {"name": "Bodhan Road", "multiplier": 1.10}],
    "Vinayak Nagar": [{"name": "Aryawaisya Colony", "multiplier": 1.10}, {"name": "Shradha Nagar", "multiplier": 1.05}, {"name": "Ngo Colony", "multiplier": 1.15}],
    "Subhash Nagar": [{"name": "Barkatpura", "multiplier": 1.05}, {"name": "Phulong", "multiplier": 1.00}, {"name": "Railway Station Area", "multiplier": 1.10}],
    "Nizamabad Rural": [{"name": "Ditchpally", "multiplier": 1.00}, {"name": "Makloor", "multiplier": 0.95}, {"name": "Jakranpally", "multiplier": 0.90}],
    "Borgaon": [{"name": "Borgaon (P)", "multiplier": 1.00}, {"name": "Borgaon (K)", "multiplier": 0.95}, {"name": "Indur", "multiplier": 1.05}],
    "Gautam Nagar": [{"name": "Shivaji Nagar", "multiplier": 1.05}, {"name": "Kanteshwar Road", "multiplier": 1.10}, {"name": "Mubaraknagar", "multiplier": 1.00}],
    "Kamareddy": [{"name": "Vidyut Nagar", "multiplier": 1.05}, {"name": "Ashok Nagar", "multiplier": 1.10}, {"name": "Devunipally", "multiplier": 1.00}],

    "Mukarampura": [{"name": "Geeta Bhavan Road", "multiplier": 1.15}, {"name": "Tower Circle", "multiplier": 1.20}, {"name": "Gandhi Road", "multiplier": 1.10}],
    "Saptagiri Colony": [{"name": "Court Road", "multiplier": 1.10}, {"name": "Kashmirgadda", "multiplier": 1.05}, {"name": "Mankammathota", "multiplier": 1.15}],
    "Kashmirgadda": [{"name": "Seetharampur", "multiplier": 1.05}, {"name": "Ashok Nagar", "multiplier": 1.10}, {"name": "Vidyanagar", "multiplier": 1.15}],
    "Vidya Nagar": [{"name": "Vavilalapally", "multiplier": 1.10}, {"name": "Bank Colony", "multiplier": 1.15}, {"name": "SRR College Area", "multiplier": 1.05}],
    "Jyothinagar": [{"name": "NTPC Area", "multiplier": 1.10}, {"name": "Godavarikhani", "multiplier": 1.05}, {"name": "Ramagundam", "multiplier": 1.00}],
    "Bhagatnagar": [{"name": "Karkhanagadda", "multiplier": 1.05}, {"name": "Mankammathota", "multiplier": 1.10}, {"name": "Housing Board Colony", "multiplier": 1.15}],
    "Mankammathota": [{"name": "Satavahana University Road", "multiplier": 1.10}, {"name": "Padmanagar", "multiplier": 1.05}, {"name": "Collectorate Area", "multiplier": 1.15}],
    "Chinthakunta": [{"name": "LMD Colony", "multiplier": 1.05}, {"name": "Kothapalli", "multiplier": 1.10}, {"name": "Thimmapur", "multiplier": 1.00}],
    "Vavilalapally": [{"name": "Bommakal Road", "multiplier": 1.10}, {"name": "Christian Colony", "multiplier": 1.05}, {"name": "Auto Nagar", "multiplier": 1.00}],
    "Hussainipura": [{"name": "Tower Circle", "multiplier": 1.10}, {"name": "Urdu Bazar", "multiplier": 1.05}, {"name": "Karkhanagadda", "multiplier": 1.00}],

    # ── Maharashtra ──
    "Andheri West": [{"name": "Lokhandwala Complex", "multiplier": 1.25}, {"name": "Versova", "multiplier": 1.20}, {"name": "Oshiwara", "multiplier": 1.10}, {"name": "Seven Bungalows", "multiplier": 1.15}, {"name": "Yari Road", "multiplier": 1.18}, {"name": "Four Bungalows", "multiplier": 1.12}],
    "Bandra West": [{"name": "Pali Hill", "multiplier": 1.40}, {"name": "Carter Road", "multiplier": 1.35}, {"name": "Linking Road", "multiplier": 1.20}, {"name": "Bandstand", "multiplier": 1.45}, {"name": "Chapel Road", "multiplier": 1.25}, {"name": "Turner Road", "multiplier": 1.30}],
    "Juhu": [{"name": "Juhu Tara Road", "multiplier": 1.35}, {"name": "JVPD Scheme", "multiplier": 1.40}, {"name": "Vile Parle West", "multiplier": 1.20}, {"name": "10th Road", "multiplier": 1.25}, {"name": "Juhu Scheme", "multiplier": 1.38}],
    "Powai": [{"name": "Hiranandani Gardens", "multiplier": 1.35}, {"name": "Rambaug Retreat", "multiplier": 1.20}, {"name": "Lake Promenade", "multiplier": 1.30}, {"name": "Chandivali", "multiplier": 1.15}, {"name": "JVLR", "multiplier": 1.25}],
    "Goregaon East": [{"name": "Oberoi Woods", "multiplier": 1.25}, {"name": "Aarey Colony", "multiplier": 1.05}, {"name": "Film City Road", "multiplier": 1.10}, {"name": "Gokuldham", "multiplier": 1.20}, {"name": "Dindoshi", "multiplier": 1.15}],
    "Malad West": [{"name": "Mindspace", "multiplier": 1.25}, {"name": "Evershine Nagar", "multiplier": 1.20}, {"name": "Orlem", "multiplier": 1.15}, {"name": "Kanchpada", "multiplier": 1.10}, {"name": "Marve Road", "multiplier": 1.05}],
    "Kandivali East": [{"name": "Lokhandwala Township", "multiplier": 1.20}, {"name": "Thakur Village", "multiplier": 1.25}, {"name": "Thakur Complex", "multiplier": 1.15}, {"name": "Akurli Road", "multiplier": 1.10}, {"name": "Growels 101 Area", "multiplier": 1.30}],
    "Borivali West": [{"name": "IC Colony", "multiplier": 1.25}, {"name": "Eksar", "multiplier": 1.15}, {"name": "Gorai", "multiplier": 1.10}, {"name": "Babhai Naka", "multiplier": 1.20}, {"name": "Yogi Nagar", "multiplier": 1.18}],
    "Colaba": [{"name": "Cuffe Parade", "multiplier": 1.40}, {"name": "Colaba Causeway", "multiplier": 1.35}, {"name": "Navy Nagar", "multiplier": 1.30}, {"name": "Apollo Bunder", "multiplier": 1.45}, {"name": "Sassoon Dock", "multiplier": 1.20}],
    "Dadar": [{"name": "Dadar West", "multiplier": 1.25}, {"name": "Shivaji Park", "multiplier": 1.35}, {"name": "Dadar East", "multiplier": 1.20}, {"name": "Parsi Colony", "multiplier": 1.30}, {"name": "Prabhadevi", "multiplier": 1.28}],
    "Worli": [{"name": "Worli Sea Face", "multiplier": 1.45}, {"name": "Prabhadevi", "multiplier": 1.35}, {"name": "Lower Parel", "multiplier": 1.30}, {"name": "Century Bazaar", "multiplier": 1.25}, {"name": "Poonam Chambers", "multiplier": 1.40}],
    "Lower Parel": [{"name": "Kamala Mills", "multiplier": 1.35}, {"name": "Phoenix Palladium Area", "multiplier": 1.40}, {"name": "Delisle Road", "multiplier": 1.20}, {"name": "N M Joshi Marg", "multiplier": 1.25}, {"name": "Peninsula Corporate Park", "multiplier": 1.38}],
    "Chembur": [{"name": "Diamond Garden", "multiplier": 1.25}, {"name": "Sindhi Society", "multiplier": 1.20}, {"name": "Tilak Nagar", "multiplier": 1.15}, {"name": "Pestom Sagar", "multiplier": 1.18}, {"name": "Basant Park", "multiplier": 1.22}],
    "Navi Mumbai": [{"name": "Vashi", "multiplier": 1.25}, {"name": "Kharghar", "multiplier": 1.20}, {"name": "Nerul", "multiplier": 1.18}, {"name": "Belapur", "multiplier": 1.22}, {"name": "Seawoods", "multiplier": 1.30}],
    "Thane": [{"name": "Ghodbunder Road", "multiplier": 1.20}, {"name": "Majiwada", "multiplier": 1.25}, {"name": "Pokhran Road", "multiplier": 1.30}, {"name": "Hiranandani Estate", "multiplier": 1.35}, {"name": "Vartak Nagar", "multiplier": 1.15}],
    "Vile Parle": [{"name": "Vile Parle East", "multiplier": 1.25}, {"name": "Vile Parle West", "multiplier": 1.30}, {"name": "Milan Subway Road", "multiplier": 1.15}, {"name": "Hanuman Road", "multiplier": 1.20}, {"name": "Irla", "multiplier": 1.28}],
    "Santacruz": [{"name": "Santacruz West", "multiplier": 1.30}, {"name": "Santacruz East", "multiplier": 1.20}, {"name": "Juhu Road", "multiplier": 1.35}, {"name": "Linking Road", "multiplier": 1.25}, {"name": "SV Road", "multiplier": 1.15}],
    "Mulund": [{"name": "Mulund West", "multiplier": 1.25}, {"name": "Mulund East", "multiplier": 1.20}, {"name": "LBS Marg", "multiplier": 1.15}, {"name": "P K Road", "multiplier": 1.22}, {"name": "Vasant Vihar", "multiplier": 1.30}],
    "Ghatkopar": [{"name": "Ghatkopar East", "multiplier": 1.25}, {"name": "Ghatkopar West", "multiplier": 1.20}, {"name": "Pant Nagar", "multiplier": 1.15}, {"name": "Garodia Nagar", "multiplier": 1.30}, {"name": "Amrut Nagar", "multiplier": 1.18}],

    "Koregaon Park": [{"name": "Lane 5", "multiplier": 1.30}, {"name": "Lane 6", "multiplier": 1.35}, {"name": "Lane 7", "multiplier": 1.40}, {"name": "Osho Ashram Area", "multiplier": 1.25}, {"name": "North Main Road", "multiplier": 1.38}],
    "Viman Nagar": [{"name": "Datta Mandir Circle", "multiplier": 1.15}, {"name": "Symbiosis Road", "multiplier": 1.20}, {"name": "Sanjay Park", "multiplier": 1.10}, {"name": "VIP Road", "multiplier": 1.25}, {"name": "Lohegaon Road", "multiplier": 1.05}],
    "Kalyani Nagar": [{"name": "Bishops School Area", "multiplier": 1.25}, {"name": "Gold Adlabs", "multiplier": 1.20}, {"name": "Marigold", "multiplier": 1.15}, {"name": "Aga Khan Palace Area", "multiplier": 1.30}, {"name": "Ramwadi", "multiplier": 1.10}],
    "Hinjewadi": [{"name": "Phase 1", "multiplier": 1.15}, {"name": "Phase 2", "multiplier": 1.10}, {"name": "Phase 3", "multiplier": 1.05}, {"name": "Blue Ridge Town", "multiplier": 1.20}, {"name": "Megapolis Circle", "multiplier": 1.12}],
    "Wakad": [{"name": "Bhumkar Chowk", "multiplier": 1.15}, {"name": "Datta Mandir Road", "multiplier": 1.10}, {"name": "Kaspate Wasti", "multiplier": 1.20}, {"name": "Pink City Road", "multiplier": 1.05}, {"name": "Hinjewadi Road", "multiplier": 1.18}],
    "Baner": [{"name": "Baner Pashan Link Road", "multiplier": 1.25}, {"name": "Balewadi High Street", "multiplier": 1.30}, {"name": "Pancard Club Road", "multiplier": 1.20}, {"name": "Pan Card Club Road", "multiplier": 1.15}, {"name": "Veerbhadra Nagar", "multiplier": 1.10}],
    "Kothrud": [{"name": "Karve Nagar", "multiplier": 1.20}, {"name": "Mayur Colony", "multiplier": 1.25}, {"name": "Paud Road", "multiplier": 1.15}, {"name": "Bhusari Colony", "multiplier": 1.10}, {"name": "Dahanukar Colony", "multiplier": 1.22}],
    "Hadapsar": [{"name": "Magarpatta City", "multiplier": 1.25}, {"name": "Amanora Park Town", "multiplier": 1.30}, {"name": "Fursungi", "multiplier": 1.05}, {"name": "Sasvad Road", "multiplier": 1.10}, {"name": "Mundhwa", "multiplier": 1.15}],
    "Kharadi": [{"name": "EON Free Zone", "multiplier": 1.25}, {"name": "Thite Nagar", "multiplier": 1.15}, {"name": "Chandan Nagar", "multiplier": 1.10}, {"name": "Wadi", "multiplier": 1.05}, {"name": "Zensar IT Park", "multiplier": 1.20}],
    "Magarpatta City": [{"name": "Destination Center", "multiplier": 1.30}, {"name": "Seasons Mall Area", "multiplier": 1.25}, {"name": "Cybercity", "multiplier": 1.35}],
    "Shivajinagar": [{"name": "FC Road", "multiplier": 1.35}, {"name": "JM Road", "multiplier": 1.30}, {"name": "Model Colony", "multiplier": 1.40}, {"name": "Gokhale Nagar", "multiplier": 1.20}, {"name": "Wakdewadi", "multiplier": 1.25}],
    "Aundh": [{"name": "DP Road", "multiplier": 1.25}, {"name": "ITI Road", "multiplier": 1.30}, {"name": "Baner Road", "multiplier": 1.20}, {"name": "Sanewadi", "multiplier": 1.35}, {"name": "Bremen Chowk", "multiplier": 1.28}],
    "Camp": [{"name": "MG Road", "multiplier": 1.35}, {"name": "East Street", "multiplier": 1.30}, {"name": "Moledina Road", "multiplier": 1.25}, {"name": "SGS Mall Area", "multiplier": 1.40}],
    "Deccan Gymkhana": [{"name": "Prabhat Road", "multiplier": 1.45}, {"name": "BMCC Road", "multiplier": 1.35}, {"name": "Bhandarkar Road", "multiplier": 1.40}, {"name": "Erandwane", "multiplier": 1.30}],
    "Bavdhan": [{"name": "Bavdhan Khurd", "multiplier": 1.20}, {"name": "Bavdhan Budruk", "multiplier": 1.15}, {"name": "NDA Road", "multiplier": 1.25}, {"name": "Pashan Road", "multiplier": 1.10}],
    "Pimple Saudagar": [{"name": "Rahatani", "multiplier": 1.25}, {"name": "Wakad Road", "multiplier": 1.20}, {"name": "Shivar Garden", "multiplier": 1.30}, {"name": "Kokane Chowk", "multiplier": 1.28}],
    "Pashan": [{"name": "Sus Road", "multiplier": 1.20}, {"name": "Pashan Sus Road", "multiplier": 1.25}, {"name": "Sutarwadi", "multiplier": 1.15}, {"name": "Pashan Lake", "multiplier": 1.10}],
    "Wagholi": [{"name": "Ubak Nagar", "multiplier": 1.10}, {"name": "Lohegaon Road", "multiplier": 1.15}, {"name": "Keshnand Road", "multiplier": 1.05}, {"name": "Baif Road", "multiplier": 1.20}],
    "Rasta Peth": [{"name": "Quarter Gate", "multiplier": 1.15}, {"name": "Nana Peth", "multiplier": 1.10}, {"name": "Somwar Peth", "multiplier": 1.20}, {"name": "KEM Hospital Area", "multiplier": 1.25}],
    "Swargate": [{"name": "Shankar Sheth Road", "multiplier": 1.20}, {"name": "Tilak Road", "multiplier": 1.25}, {"name": "Gultekdi", "multiplier": 1.15}, {"name": "Mukund Nagar", "multiplier": 1.30}],

    # ── Delhi ──
    "Connaught Place": [{"name": "Inner Circle", "multiplier": 1.30}, {"name": "Outer Circle", "multiplier": 1.15}, {"name": "Middle Circle", "multiplier": 1.20}, {"name": "Palika Bazaar", "multiplier": 1.10}, {"name": "Janpath", "multiplier": 1.25}, {"name": "Barakhamba Road", "multiplier": 1.35}],
    "Hauz Khas": [{"name": "Hauz Khas Village", "multiplier": 1.25}, {"name": "SDA", "multiplier": 1.15}, {"name": "Hauz Khas Enclave", "multiplier": 1.20}, {"name": "Green Park", "multiplier": 1.30}],
    "Vasant Kunj": [{"name": "Sector A", "multiplier": 1.25}, {"name": "Sector B", "multiplier": 1.30}, {"name": "Sector C", "multiplier": 1.20}, {"name": "Sector D", "multiplier": 1.15}, {"name": "Vasant Vihar", "multiplier": 1.35}],
    "Saket": [{"name": "J Block", "multiplier": 1.20}, {"name": "M Block", "multiplier": 1.15}, {"name": "E Block", "multiplier": 1.10}, {"name": "Press Enclave", "multiplier": 1.25}, {"name": "Malviya Nagar", "multiplier": 1.18}],
    "Dwarka": [{"name": "Sector 6", "multiplier": 1.15}, {"name": "Sector 10", "multiplier": 1.20}, {"name": "Sector 11", "multiplier": 1.10}, {"name": "Sector 22", "multiplier": 1.25}, {"name": "Sector 12", "multiplier": 1.18}],
    "Rohini": [{"name": "Sector 9", "multiplier": 1.15}, {"name": "Sector 11", "multiplier": 1.10}, {"name": "Sector 13", "multiplier": 1.20}, {"name": "Sector 14", "multiplier": 1.12}, {"name": "Sector 8", "multiplier": 1.08}],
    "Greater Kailash": [{"name": "GK 1", "multiplier": 1.35}, {"name": "GK 2", "multiplier": 1.30}, {"name": "M Block Market", "multiplier": 1.40}, {"name": "N Block Market", "multiplier": 1.38}, {"name": "East of Kailash", "multiplier": 1.25}],
    "Janakpuri": [{"name": "C Block", "multiplier": 1.20}, {"name": "B Block", "multiplier": 1.15}, {"name": "A Block", "multiplier": 1.10}, {"name": "D Block", "multiplier": 1.25}, {"name": "Vikas Puri", "multiplier": 1.18}],
    "Lajpat Nagar": [{"name": "Lajpat Nagar 1", "multiplier": 1.15}, {"name": "Lajpat Nagar 2", "multiplier": 1.20}, {"name": "Lajpat Nagar 3", "multiplier": 1.25}, {"name": "Lajpat Nagar 4", "multiplier": 1.30}, {"name": "Amar Colony", "multiplier": 1.18}],
    "Karol Bagh": [{"name": "Gaffar Market", "multiplier": 1.20}, {"name": "Ajmal Khan Road", "multiplier": 1.25}, {"name": "WEA", "multiplier": 1.30}, {"name": "Bapa Nagar", "multiplier": 1.15}, {"name": "Dev Nagar", "multiplier": 1.10}],
    "Pitampura": [{"name": "Kohat Enclave", "multiplier": 1.25}, {"name": "Saraswati Vihar", "multiplier": 1.20}, {"name": "Rani Bagh", "multiplier": 1.15}, {"name": "Lok Vihar", "multiplier": 1.10}, {"name": "Harsh Vihar", "multiplier": 1.18}],
    "Vasant Vihar": [{"name": "Vasant Vihar Block A", "multiplier": 1.35}, {"name": "Vasant Vihar Block B", "multiplier": 1.40}, {"name": "Vasant Vihar Block C", "multiplier": 1.30}, {"name": "Vasant Vihar Block D", "multiplier": 1.25}, {"name": "Munirka", "multiplier": 1.15}],
    "Rajouri Garden": [{"name": "Main Market", "multiplier": 1.25}, {"name": "Subhash Nagar", "multiplier": 1.15}, {"name": "Tagore Garden", "multiplier": 1.20}, {"name": "Shivaji Enclave", "multiplier": 1.10}, {"name": "Vishal Enclave", "multiplier": 1.30}],
    "Def Col": [{"name": "A Block", "multiplier": 1.40}, {"name": "B Block", "multiplier": 1.45}, {"name": "C Block", "multiplier": 1.35}, {"name": "D Block", "multiplier": 1.30}, {"name": "Kotla Mubarakpur", "multiplier": 1.15}],
    "Malviya Nagar": [{"name": "Khirki Extension", "multiplier": 1.10}, {"name": "Sheikh Sarai", "multiplier": 1.15}, {"name": "Panchsheel Vihar", "multiplier": 1.20}, {"name": "Geetanjali Enclave", "multiplier": 1.35}, {"name": "Shivalik", "multiplier": 1.30}],
    "South Ex": [{"name": "South Ex Part 1", "multiplier": 1.40}, {"name": "South Ex Part 2", "multiplier": 1.45}, {"name": "NDSE Part 1", "multiplier": 1.35}, {"name": "NDSE Part 2", "multiplier": 1.30}, {"name": "Andrews Ganj", "multiplier": 1.25}],
    "Green Park": [{"name": "Green Park Main", "multiplier": 1.40}, {"name": "Green Park Extension", "multiplier": 1.35}, {"name": "Safdarjung Enclave", "multiplier": 1.30}, {"name": "Yusuf Sarai", "multiplier": 1.20}, {"name": "Gautam Nagar", "multiplier": 1.15}],
    "Chanakyapuri": [{"name": "Diplomatic Enclave", "multiplier": 1.50}, {"name": "Malcha Marg", "multiplier": 1.45}, {"name": "Shanti Path", "multiplier": 1.40}, {"name": "Yashwant Place", "multiplier": 1.35}, {"name": "Satya Marg", "multiplier": 1.30}],
    "Nehru Place": [{"name": "Kalkaji", "multiplier": 1.20}, {"name": "CR Park", "multiplier": 1.25}, {"name": "Govindpuri", "multiplier": 1.10}, {"name": "East of Kailash", "multiplier": 1.30}, {"name": "Kailash Colony", "multiplier": 1.35}],
    "Laxmi Nagar": [{"name": "Shakarpur", "multiplier": 1.10}, {"name": "Preet Vihar", "multiplier": 1.25}, {"name": "Nirman Vihar", "multiplier": 1.20}, {"name": "Patparganj", "multiplier": 1.15}, {"name": "Mayur Vihar", "multiplier": 1.30}],

    # ── Tamil Nadu ──
    "T Nagar": [{"name": "Panagal Park", "multiplier": 1.25}, {"name": "Pondy Bazaar", "multiplier": 1.30}, {"name": "Rangarajapuram", "multiplier": 1.10}, {"name": "GN Chetty Road", "multiplier": 1.20}, {"name": "Usman Road", "multiplier": 1.15}],
    "Adyar": [{"name": "Gandhi Nagar", "multiplier": 1.25}, {"name": "Indira Nagar", "multiplier": 1.20}, {"name": "Kasturba Nagar", "multiplier": 1.30}, {"name": "LB Road", "multiplier": 1.15}, {"name": "Besant Nagar", "multiplier": 1.35}],
    "Anna Nagar": [{"name": "Shanthi Colony", "multiplier": 1.30}, {"name": "Blue Star", "multiplier": 1.20}, {"name": "Thirumangalam", "multiplier": 1.15}, {"name": "Roundtana", "multiplier": 1.25}, {"name": "Anna Nagar East", "multiplier": 1.22}],
    "Velachery": [{"name": "100 Feet Bypass Road", "multiplier": 1.20}, {"name": "Vijayanagar Bus Terminus", "multiplier": 1.15}, {"name": "Taramani Link Road", "multiplier": 1.10}, {"name": "Baby Nagar", "multiplier": 1.05}, {"name": "Guindy", "multiplier": 1.25}],
    "Mylapore": [{"name": "Luz", "multiplier": 1.30}, {"name": "Mandaveli", "multiplier": 1.25}, {"name": "Santhome", "multiplier": 1.35}, {"name": "Royapettah", "multiplier": 1.20}, {"name": "Alwarpet", "multiplier": 1.40}],
    "Alwarpet": [{"name": "TTK Road", "multiplier": 1.35}, {"name": "Bheemanna Mudali Garden", "multiplier": 1.25}, {"name": "St Marys Road", "multiplier": 1.30}, {"name": "Cenotaph Road", "multiplier": 1.45}, {"name": "Boat Club", "multiplier": 1.50}],
    "Besant Nagar": [{"name": "Elliots Beach Road", "multiplier": 1.40}, {"name": "Kalakshetra Colony", "multiplier": 1.35}, {"name": "Arundale Beach Road", "multiplier": 1.30}, {"name": "Thiruvanmiyur", "multiplier": 1.25}, {"name": "Vannandurai", "multiplier": 1.20}],
    "Nungambakkam": [{"name": "Khader Nawaz Khan Road", "multiplier": 1.45}, {"name": "Sterling Road", "multiplier": 1.35}, {"name": "Mahalingapuram", "multiplier": 1.30}, {"name": "Village Road", "multiplier": 1.25}, {"name": "Chetpet", "multiplier": 1.20}],
    "Tambaram": [{"name": "East Tambaram", "multiplier": 1.15}, {"name": "West Tambaram", "multiplier": 1.20}, {"name": "Selaiyur", "multiplier": 1.10}, {"name": "Chromepet", "multiplier": 1.25}, {"name": "Perungalathur", "multiplier": 1.05}],
    "Guindy": [{"name": "Kathipara", "multiplier": 1.25}, {"name": "Ekkatuthangal", "multiplier": 1.20}, {"name": "Race Course", "multiplier": 1.30}, {"name": "Little Mount", "multiplier": 1.15}, {"name": "Saidapet", "multiplier": 1.10}],

    # ── West Bengal ──
    "Salt Lake": [{"name": "Sector I", "multiplier": 1.20}, {"name": "Sector II", "multiplier": 1.25}, {"name": "Sector III", "multiplier": 1.15}, {"name": "Sector V (IT Hub)", "multiplier": 1.30}, {"name": "Karunamoyee", "multiplier": 1.18}],
    "New Town": [{"name": "Action Area I", "multiplier": 1.15}, {"name": "Action Area II", "multiplier": 1.20}, {"name": "Action Area III", "multiplier": 1.10}, {"name": "Eco Park Area", "multiplier": 1.25}, {"name": "Rajarhat", "multiplier": 1.05}],
    "Ballygunge": [{"name": "Ballygunge Circular Road", "multiplier": 1.35}, {"name": "Gushtia", "multiplier": 1.20}, {"name": "Ballygunge Park", "multiplier": 1.40}, {"name": "Gariahat Road", "multiplier": 1.25}, {"name": "Ballygunge Place", "multiplier": 1.30}],
    "Alipore": [{"name": "New Alipore", "multiplier": 1.35}, {"name": "Alipore Road", "multiplier": 1.45}, {"name": "Belvedere Road", "multiplier": 1.40}, {"name": "Judges Court Road", "multiplier": 1.30}, {"name": "Chetla", "multiplier": 1.20}],
    "Jadavpur": [{"name": "Jadavpur University Area", "multiplier": 1.25}, {"name": "Dhakuria", "multiplier": 1.20}, {"name": "Santoshpur", "multiplier": 1.15}, {"name": "Baghajatin", "multiplier": 1.10}, {"name": "Garia", "multiplier": 1.05}],

    # ── Gujarat ──
    "SG Highway": [{"name": "Makarba", "multiplier": 1.15}, {"name": "Gota Cross Road", "multiplier": 1.10}, {"name": "Sola", "multiplier": 1.20}, {"name": "Vaishnodevi Circle", "multiplier": 1.05}, {"name": "Thaltej", "multiplier": 1.25}],
    "Bopal": [{"name": "South Bopal (SoBo)", "multiplier": 1.20}, {"name": "Bopal Lake", "multiplier": 1.10}, {"name": "TRP Mall Area", "multiplier": 1.15}, {"name": "Ghuma", "multiplier": 1.05}, {"name": "Ambli", "multiplier": 1.25}],
    "Satellite": [{"name": "Prahlad Nagar", "multiplier": 1.30}, {"name": "Anand Nagar", "multiplier": 1.25}, {"name": "Shyamal", "multiplier": 1.20}, {"name": "Shivranjani", "multiplier": 1.15}, {"name": "Jodhpur", "multiplier": 1.10}],
    "Vastrapur": [{"name": "Vastrapur Lake", "multiplier": 1.35}, {"name": "IIM Road", "multiplier": 1.40}, {"name": "Drive In Road", "multiplier": 1.25}, {"name": "Bodakdev", "multiplier": 1.30}, {"name": "Gurukul", "multiplier": 1.20}],

    # ── Uttar Pradesh ──
    "Sector 62": [{"name": "Institutional Area", "multiplier": 1.20}, {"name": "Fortis Hospital Area", "multiplier": 1.15}, {"name": "Electronic City Metro", "multiplier": 1.25}, {"name": "Sector 63", "multiplier": 1.10}, {"name": "Sector 59", "multiplier": 1.05}],
    "Sector 137": [{"name": "Paras Tierea", "multiplier": 1.15}, {"name": "Exotica Fresco", "multiplier": 1.20}, {"name": "Paramount Floraville", "multiplier": 1.10}, {"name": "Sector 143", "multiplier": 1.05}, {"name": "Sector 135", "multiplier": 1.25}],
    "Gomti Nagar": [{"name": "Vibhuti Khand", "multiplier": 1.25}, {"name": "Gomti Nagar Extension", "multiplier": 1.20}, {"name": "Patrakar Puram", "multiplier": 1.15}, {"name": "Manoj Pandey Chauraha", "multiplier": 1.10}, {"name": "Viraj Khand", "multiplier": 1.30}],
    "Hazratganj": [{"name": "Ashok Marg", "multiplier": 1.35}, {"name": "Park Road", "multiplier": 1.30}, {"name": "Gokhale Marg", "multiplier": 1.25}, {"name": "Jopling Road", "multiplier": 1.20}, {"name": "Vidhan Sabha Marg", "multiplier": 1.40}],

    # ── Rajasthan ──
    "Malviya Nagar": [{"name": "Sector 1", "multiplier": 1.15}, {"name": "Sector 2", "multiplier": 1.20}, {"name": "JLN Marg", "multiplier": 1.25}, {"name": "Gaurav Tower Area", "multiplier": 1.30}, {"name": "Model Town", "multiplier": 1.10}],
    "Vaishali Nagar": [{"name": "Amrapali Circle", "multiplier": 1.25}, {"name": "Gandhi Path", "multiplier": 1.20}, {"name": "Chitrakoot", "multiplier": 1.15}, {"name": "Queens Road", "multiplier": 1.30}, {"name": "Shyam Nagar", "multiplier": 1.10}],
}
